#pragma once
#ifndef BOOTLOADER
#define BOOTLOADER

#include "typedefs.h"

#define BOOTLOADER_BASE_ADDRESS			((size_t)&__PTR_BOOTLOADER_BASE_ADDRESS__)
#define BOOTLOADER_END_ADDRESS			((size_t)&__PTR_BOOTLOADER_END_ADDRESS__)
#define BOOTLOADER_SIZE					(BOOTLOADER_END_ADDRESS - BOOTLOADER_BASE_ADDRESS)
#define BOOTLOADER_LENGTH				(ALIGN_UP(BOOTLOADER_SIZE, 512) / 512)
#define BOOTLOADER_START_SECTOR_LBA		0x0001
#define BOOTLOADER_END_SECTOR_LBA		(BOOTLOADER_START_SECTOR_LBA + BOOTLOADER_LENGTH)
#define BOOTLOADER_START_SECTOR			(BOOTLOADER_START_SECTOR_LBA + 1)
#define BOOTLOADER_END_SECTOR			(BOOTLOADER_END_SECTOR_LBA + 1)

extern size_t __PTR_BOOTLOADER_BASE_ADDRESS__;
extern size_t __PTR_BOOTLOADER_END_ADDRESS__;

#endif