bits 32

extern KernelDataSegValue
extern SoftwareInterruptHandler

%macro SOFTWARE_INT_HANDLER_NO_ERROR	1
extern SoftwareIntHandler%1
SoftwareIntHandler%1:
	push 0
	push %1
	jmp CommonSoftwareIntHandlerStub
%endmacro

%macro SOFTWARE_INT_HANDLER_ERROR		1
extern SoftwareIntHandler%1
SoftwareIntHandler%1:
	push %1
	jmp CommonSoftwareIntHandlerStub
%endmacro

SOFTWARE_INT_HANDLER_NO_ERROR	0
SOFTWARE_INT_HANDLER_NO_ERROR	1
SOFTWARE_INT_HANDLER_NO_ERROR	2
SOFTWARE_INT_HANDLER_NO_ERROR	3
SOFTWARE_INT_HANDLER_NO_ERROR	4
SOFTWARE_INT_HANDLER_NO_ERROR	5
SOFTWARE_INT_HANDLER_NO_ERROR	6
SOFTWARE_INT_HANDLER_NO_ERROR	7
SOFTWARE_INT_HANDLER_ERROR		8
SOFTWARE_INT_HANDLER_NO_ERROR	9
SOFTWARE_INT_HANDLER_ERROR		10
SOFTWARE_INT_HANDLER_ERROR		11
SOFTWARE_INT_HANDLER_ERROR		12
SOFTWARE_INT_HANDLER_ERROR		13
SOFTWARE_INT_HANDLER_ERROR		14
SOFTWARE_INT_HANDLER_NO_ERROR	15
SOFTWARE_INT_HANDLER_NO_ERROR	16
SOFTWARE_INT_HANDLER_ERROR		17
SOFTWARE_INT_HANDLER_NO_ERROR	18
SOFTWARE_INT_HANDLER_NO_ERROR	19
SOFTWARE_INT_HANDLER_NO_ERROR	20
SOFTWARE_INT_HANDLER_ERROR		21
SOFTWARE_INT_HANDLER_NO_ERROR	22
SOFTWARE_INT_HANDLER_NO_ERROR	23
SOFTWARE_INT_HANDLER_NO_ERROR	24
SOFTWARE_INT_HANDLER_NO_ERROR	25
SOFTWARE_INT_HANDLER_NO_ERROR	26
SOFTWARE_INT_HANDLER_NO_ERROR	27
SOFTWARE_INT_HANDLER_NO_ERROR	28
SOFTWARE_INT_HANDLER_ERROR		29
SOFTWARE_INT_HANDLER_ERROR		30
SOFTWARE_INT_HANDLER_NO_ERROR	31

CommonSoftwareIntHandlerStub:
	pusha
	push ds
	push es
	push fs
	push gs
	mov eax, 0x10
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	mov eax, esp
	push eax
	call SoftwareInterruptHandler
	pop eax
	pop gs
	pop fs
	pop es
	pop ds
	popa
	add esp, 8
	iret