bits 32

extern SoftwareInterruptHandler
extern HardwareInterruptHandler

%macro SOFTWARE_INT_HANDLER_NO_ERROR	1
extern SoftwareIntHandler%1
SoftwareIntHandler%1:
	push 0
	push %1
	jmp CommonSoftwareIntHandlerStub
%endmacro

%macro SOFTWARE_INT_HANDLER_ERROR		1
extern SoftwareIntHandler%1
SoftwareIntHandler%1:
	push %1
	jmp CommonSoftwareIntHandlerStub
%endmacro

%macro HARDWARE_INT_HANDLER				1
extern HardwareIntHandler%1
HardwareIntHandler%1:
	push 0
	push %1+32
	jmp CommonHardwareIntHandlerStub
%endmacro

SOFTWARE_INT_HANDLER_NO_ERROR	0
SOFTWARE_INT_HANDLER_NO_ERROR	1
SOFTWARE_INT_HANDLER_NO_ERROR	2
SOFTWARE_INT_HANDLER_NO_ERROR	3
SOFTWARE_INT_HANDLER_NO_ERROR	4
SOFTWARE_INT_HANDLER_NO_ERROR	5
SOFTWARE_INT_HANDLER_NO_ERROR	6
SOFTWARE_INT_HANDLER_NO_ERROR	7
SOFTWARE_INT_HANDLER_ERROR		8
SOFTWARE_INT_HANDLER_NO_ERROR	9
SOFTWARE_INT_HANDLER_ERROR		10
SOFTWARE_INT_HANDLER_ERROR		11
SOFTWARE_INT_HANDLER_ERROR		12
SOFTWARE_INT_HANDLER_ERROR		13
SOFTWARE_INT_HANDLER_ERROR		14
SOFTWARE_INT_HANDLER_NO_ERROR	15
SOFTWARE_INT_HANDLER_NO_ERROR	16
SOFTWARE_INT_HANDLER_ERROR		17
SOFTWARE_INT_HANDLER_NO_ERROR	18
SOFTWARE_INT_HANDLER_NO_ERROR	19
SOFTWARE_INT_HANDLER_NO_ERROR	20
SOFTWARE_INT_HANDLER_ERROR		21
SOFTWARE_INT_HANDLER_NO_ERROR	22
SOFTWARE_INT_HANDLER_NO_ERROR	23
SOFTWARE_INT_HANDLER_NO_ERROR	24
SOFTWARE_INT_HANDLER_NO_ERROR	25
SOFTWARE_INT_HANDLER_NO_ERROR	26
SOFTWARE_INT_HANDLER_NO_ERROR	27
SOFTWARE_INT_HANDLER_NO_ERROR	28
SOFTWARE_INT_HANDLER_ERROR		29
SOFTWARE_INT_HANDLER_ERROR		30
SOFTWARE_INT_HANDLER_NO_ERROR	31

HARDWARE_INT_HANDLER			0
HARDWARE_INT_HANDLER			1
HARDWARE_INT_HANDLER			2
HARDWARE_INT_HANDLER			3
HARDWARE_INT_HANDLER			4
HARDWARE_INT_HANDLER			5
HARDWARE_INT_HANDLER			6
HARDWARE_INT_HANDLER			7
HARDWARE_INT_HANDLER			8
HARDWARE_INT_HANDLER			9
HARDWARE_INT_HANDLER			10
HARDWARE_INT_HANDLER			11
HARDWARE_INT_HANDLER			12
HARDWARE_INT_HANDLER			13
HARDWARE_INT_HANDLER			14
HARDWARE_INT_HANDLER			15

CommonSoftwareIntHandlerStub:
	pusha
	push ds
	push es
	push fs
	push gs
	mov ax, 0x10
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	mov eax, esp
	push eax
	call SoftwareInterruptHandler
	pop eax
	pop gs
	pop fs
	pop es
	pop ds
	popa
	add esp, 8
	iret

CommonHardwareIntHandlerStub:
	pusha
	push ds
	push es
	push fs
	push gs
	mov ax, 0x10
	mov ds, ax
	mov es, ax
	mov fs, ax
	mov gs, ax
	mov eax, esp
	push eax
	call HardwareInterruptHandler
	pop eax
	pop gs
	pop fs
	pop es
	pop ds
	popa
	add esp, 8
	iret