#pragma once
#ifndef BIOS_COLORS
#define BIOS_COLORS

#include "typedefs.h"

#define BIOS_COLOR_BLACK			0x00
#define BIOS_COLOR_BLUE				0x01
#define BIOS_COLOR_GREEN			0x02
#define BIOS_COLOR_CYAN				0x03
#define BIOS_COLOR_RED				0x04
#define BIOS_COLOR_MAGENTA			0x05
#define BIOS_COLOR_BROWN			0x06
#define BIOS_COLOR_LIGHT_GRAY		0x07
#define BIOS_COLOR_DARK_GRAY		0x08
#define BIOS_COLOR_LIGHT_BLUE		0x09
#define BIOS_COLOR_LIGHT_GREEN		0x0A
#define BIOS_COLOR_LIGHT_CYAN		0x0B
#define BIOS_COLOR_LIGHT_RED		0x0C
#define BIOS_COLOR_LIGHT_MAGENTA	0x0D
#define BIOS_COLOR_YELLOW			0x0E
#define BIOS_COLOR_WHITE			0x0F

typedef UCHAR BIOS_COLOR;

#endif