#pragma once
#ifndef PS2_CTRL
#define PS2_CTRL

#include "port.h"

#define PS2_CTRL_PORT_DATA								0x60
#define PS2_CTRL_PORT_STATUS							0x64
#define PS2_CTRL_PORT_COMMAND							0x64

#define PS2_CTRL_STATUS_OUTPUT_FULL						0x01
#define PS2_CTRL_STATUS_INPUT_FULL						0x02
#define PS2_CTRL_STATUS_SYSTEM							0x04
#define PS2_CTRL_STATUS_CMD_DATA						0x08
#define PS2_CTRL_STATUS_TIMEOUT_ERROR					0x40
#define PS2_CTRL_STATUS_PARITY_ERROR					0x80

#define PS2_CTRL_COMMAND_READ_CONFIG					0x20
#define PS2_CTRL_COMMAND_WRITE_CONFIG					0x60
#define PS2_CTRL_COMMAND_DISABLE_SECOND_PORT			0xA7
#define PS2_CTRL_COMMAND_ENABLE_SECOND_PORT				0xA8

/*
	0 - passed
	1 - clock line stuck low
	2 - clock line stuck high
	3 - data line stuck low
	4 - data line stuck high
*/
#define PS2_CTRL_COMMAND_TEST_SECOND_PORT				0xA9

/*
	0x55 - passed
	0xFC - failed
*/
#define PS2_CTRL_COMMAND_TEST_CTRL						0xAA

/*
	0 - passed
	1 - clock line stuck low
	2 - clock line stuck high
	3 - data line stuck low
	4 - data line stuck high
*/
#define PS2_CTRL_COMMAND_TEST_FIRST_PORT				0xAB

#define PS2_CTRL_COMMAND_DISABLE_FIRST_PORT				0xAD
#define PS2_CTRL_COMMAND_ENABLE_FIRST_PORT				0xAE
#define PS2_CTRL_COMMAND_READ_OUTPUT					0xD0
#define PS2_CTRL_COMMAND_WRITE_OUTPUT					0xD1
#define PS2_CTRL_COMMAND_WRITE_SECOND_PORT				0xD4
#define PS2_CTRL_COMMAND_PULSE_OUTPUT_LINE				0xFE

#define PS2_CTRL_CONFIG_FIRST_PORT_INT_ENABLED			0x01
#define PS2_CTRL_CONFIG_SECOND_PORT_INT_ENABLED			0x02
#define PS2_CTRL_CONFIG_SYSTEM							0x04
#define PS2_CTRL_CONFIG_FIRST_PORT_CLOCK_DISABLED		0x10
#define PS2_CTRL_CONFIG_SECOND_PORT_CLOCK_DISABLED		0x20
#define PS2_CTRL_CONFIG_FIRST_PORT_TRANSLATION			0x40

#define PS2_CTRL_OUTPUT_SYSTEM_RESET					0x01
#define PS2_CTRL_OUTPUT_A20_GATE						0x02
#define PS2_CTRL_OUTPUT_SECOND_PORT_CLOCK				0x04
#define PS2_CTRL_OUTPUT_SECOND_PORT_DATA				0x08
#define PS2_CTRL_OUTPUT_BUFFER_FILLED_WITH_FIRST_PORT	0x10
#define PS2_CTRL_OUTPUT_BUFFER_FILLED_WITH_SECOND_PORT	0x20
#define PS2_CTRL_OUTPUT_FIRST_PORT_CLOCK				0x40
#define PS2_CTRL_OUTPUT_SECOND_PORT_CLOCK				0x80

#define PS2_CTRL_RESPONSE_TEST_PASSED					0x55
#define PS2_CTRL_RESPONSE_TEST_FAILED					0xFC
#define PS2_CTRL_RESPONSE_PORT_TEST_PASSED				0x00
#define PS2_CTRL_RESPONSE_RESET_PASSED					0xFA
#define PS2_CTRL_RESPONSE_RESET_FAILED					0xFC

VOID

#endif